CREATE TABLE listings (
    id INT PRIMARY KEY,
    listing_url VARCHAR(255),
    scrape_id INT,
    last_scraped DATE,
    source VARCHAR(255),
    name VARCHAR(255),
    neighborhood_overview TEXT,
    picture_url VARCHAR(255),
    host_id INT,
    host_url VARCHAR(255),
    host_name VARCHAR(255),
    host_since DATE,
    host_location VARCHAR(255),
    host_about TEXT,
    host_response_time VARCHAR(50),
    host_response_rate VARCHAR(10),
    host_acceptance_rate VARCHAR(10),
    host_is_superhost CHAR(1),
    host_thumbnail_url VARCHAR(255),
    host_picture_url VARCHAR(255),
    host_neighbourhood VARCHAR(255),
    host_listings_count INT,
    host_total_listings_count INT,
    host_verifications VARCHAR(255),
    host_has_profile_pic CHAR(1),
    host_identity_verified CHAR(1),
    neighbourhood VARCHAR(255),
    neighbourhood_cleansed VARCHAR(255),
    latitude DECIMAL(10, 7),
    longitude DECIMAL(10, 7),
    property_type VARCHAR(255),
    room_type VARCHAR(255),
    accommodates INT,
    bathrooms_text VARCHAR(255),
    beds INT,
    amenities VARCHAR(255),
    price FLOAT,
    minimum_nights INT,
    maximum_nights INT,
    minimum_minimum_nights INT,
    maximum_minimum_nights INT,
    minimum_maximum_nights INT,
    maximum_maximum_nights INT,
    minimum_nights_avg_ntm INT,
    maximum_nights_avg_ntm INT,
    has_availability CHAR(1),
    availability_30 INT,
    availability_60 INT,
    availability_90 INT,
    availability_365 INT,
    number_of_reviews INT,
    number_of_reviews_ltm INT,
    number_of_reviews_l30d INT,
    first_review DATE,
    last_review DATE,
    review_scores_rating DECIMAL(3, 2),
    review_scores_accuracy DECIMAL(3, 2),
    review_scores_cleanliness DECIMAL(3, 2),
    review_scores_checkin DECIMAL(3, 2),
    review_scores_communication DECIMAL(3, 2),
    review_scores_location DECIMAL(3, 2),
    review_scores_value DECIMAL(3, 2),
    license VARCHAR(20),
    instant_bookable CHAR(1),
    calculated_host_listings_count INT,
    calculated_host_listings_count_entire_homes INT,
    calculated_host_listings_count_private_rooms INT,
    calculated_host_listings_count_shared_rooms INT,
    reviews_per_month DECIMAL(3, 2)
);